### ISSUE TITLE
Crafting does not remove materials 

### ISSUE THREAD

**Issue by parham-ebrahim** [Hiype/hiype-construction#1]
When crafting for the items,
it does not take the required items from your inventory. 
so you can craft indefinitely !

**Comment by parham-ebrahim** [comment]
Fix:
line 835 or 836:
Replace
RemoveAllItems(data)
with
RemoveAllItems(Config.ItemRequirements[data.name] )

**Comment by Hiype** [comment]
Thank you! Sorry for being so late but I added the fix,
Note: Pull requests are made exactly for this.
